import React from "react";
import { Link2Icon } from "@radix-ui/react-icons";

import { InputWithLabel } from "./ui/inputWithLabel";
import { Label } from "./ui/label";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "./ui/select";

import {
  controlnetTypeIds,
  models,
  schedulers,
  SDAVariableParameters,
} from "@/types/StableDiffusionApi";
import { Separator } from "./ui/separator";

import { ScrollArea } from "./ui/scroll-area";
import { NUMBER_OF_GENERATED_QR } from "@/constants/api";
import { LabelWithTooltip } from "./ui/labelWithTooltip";

export type InitialVariablesMenu = Omit<
  SDAVariableParameters,
  "prompt" | "initImage" | "controlImage"
>;

export const initialVariables: InitialVariablesMenu = {
  modelID: "ghostmix",
  controlModel: "qrcode",
  controlType: "qrcode",
  width: 512,
  height: 512,
  strength: 0.75,
  numInferenceSteps: 30,
  samples: NUMBER_OF_GENERATED_QR,
  guidanceScale: 7.5,
  scheduler: null,
};

interface MenuAttributesProps {
  label?: React.ReactElement | string;
  className?: string;
  onChange?: (variables: InitialVariablesMenu) => void;
}

type PayloadTypes = {
  [K in keyof InitialVariablesMenu]: InitialVariablesMenu[K];
};

interface ActionVariables<K extends keyof InitialVariablesMenu> {
  key: K;
  payload: PayloadTypes[K];
}

const reducerVariables = <K extends keyof InitialVariablesMenu>(
  state: InitialVariablesMenu,
  action: ActionVariables<K>
) => {
  state[action.key] = action.payload;
  return { ...state };
};

export const MenuAttributes = (props: MenuAttributesProps) => {
  const { label, className, onChange } = props;

  const [state, dispatch] = React.useReducer(
    reducerVariables,
    initialVariables
  );

  const onHandleChange = <
    K extends keyof InitialVariablesMenu,
    P extends InitialVariablesMenu[K]
  >(
    key: K,
    payload: P
  ) => dispatch({ key, payload });

  React.useEffect(() => {
    if (onChange) {
      onChange(state);
    }
  }, [state, onChange]);

  return (
    <div className={className}>
      {label && (
        <LabelWithTooltip
          label={label}
          tooltip={{
            content: (
              <div className="text-center">
                These parameters will be the ones that have <br /> the most
                impact on the final result.
              </div>
            ),
          }}
        />
      )}
      <Separator orientation="horizontal" className="bg-slate-300 mt-1 mb-2" />
      <div className="flex flex-col w-full gap-y-4">
        <div className="flex w-full gap-x-3 mt-2">
          <div className="flex flex-col w-1/2">
            <LabelWithTooltip
              className="mb-2 text-slate-400"
              label="Image model"
              tooltip={{
                content: (
                  <div className="text-center">
                    The image model is in charge of interpreting the prompt{" "}
                    <br /> and giving us the best possible result.{" "}
                    <span className="font-bold">More models will be load.</span>
                  </div>
                ),
              }}
            />
            <Select
              defaultValue={state.modelID}
              onValueChange={(value: InitialVariablesMenu["modelID"]) =>
                onHandleChange("modelID", value)
              }
            >
              <SelectTrigger className="w-full bg-white">
                <SelectValue placeholder="Model ID" />
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  {models.map((modelId) => (
                    <SelectItem key={modelId} value={modelId}>
                      {modelId}
                    </SelectItem>
                  ))}
                </SelectGroup>
              </SelectContent>
            </Select>
          </div>
          <div className="flex flex-col w-1/2">
            <LabelWithTooltip
              className="mb-2 text-slate-400"
              label="Controlnet model"
              tooltip={{
                content: (
                  <div className="text-center">
                    controlnet is a plugin that given a initial image (the one
                    generated by the image model) <br />
                    and a control image (the QR code in our case), is able to
                    blend them in an optimal way. <br />
                    <span className="font-bold">
                      qrcode model is the only one able to provide QR-fied
                      images for now.
                    </span>
                  </div>
                ),
              }}
            />
            <Select
              disabled
              defaultValue={state.controlModel}
              onValueChange={(value: InitialVariablesMenu["controlModel"]) => (
                onHandleChange("controlModel", value),
                onHandleChange("controlType", value)
              )}
            >
              <SelectTrigger className="w-full bg-white">
                <SelectValue placeholder="Controlnet ID" />
              </SelectTrigger>
              <ScrollArea className="h-[200]">
                <SelectContent>
                  <SelectGroup>
                    {controlnetTypeIds.map((controlnetTypeId) => (
                      <SelectItem
                        key={controlnetTypeId}
                        value={controlnetTypeId}
                      >
                        {controlnetTypeId}
                      </SelectItem>
                    ))}
                  </SelectGroup>
                </SelectContent>
              </ScrollArea>
            </Select>
          </div>
        </div>
        <div className="flex w-full gap-x-3 mt-1">
          <div className="flex w-1/2 gap-2 items-end">
            <InputWithLabel
              id="width"
              tooltip={{
                content: <div>1:1 aspect ratio improves the results</div>,
              }}
              label={<span className="text-slate-400">Width</span>}
              type="number"
              placeholder="512"
              value={state.width}
              onChange={(value: string) => (
                onHandleChange("height", Number(value)),
                onHandleChange("width", Number(value))
              )}
            />
            <Link2Icon className="w-9 h-9" />
            <InputWithLabel
              id="height"
              label={<span className="text-slate-400">Height</span>}
              type="number"
              placeholder="512"
              value={state.height}
              onChange={(value: string) => (
                onHandleChange("height", Number(value)),
                onHandleChange("width", Number(value))
              )}
            />
          </div>
          <div className="flex w-1/2 gap-2 items-end">
            <InputWithLabel
              id="strength"
              label={<span className="text-slate-400">Strength</span>}
              type="text"
              placeholder="0.75"
              value={state.strength}
              onChange={(value: any) => onHandleChange("strength", value)}
              tooltip={{
                content: (
                  <div className="text-center">
                    <span className="font-bold">Range: 0.1 to 1.0. </span>{" "}
                    <br />
                    Represents the strength of the provided initial image in the
                    final result. <br /> 1.0 means that the provided image will
                    be totally destroyed.
                    <br />
                    <span className="font-bold">
                      Fixed to 1.0 by the API. Not clear the impact on the
                      results.
                    </span>
                  </div>
                ),
              }}
            />
            <InputWithLabel
              id="steps"
              label={<span className="text-slate-400">Steps</span>}
              type="number"
              placeholder="30"
              value={state.numInferenceSteps}
              onChange={(value) =>
                onHandleChange("numInferenceSteps", Number(value))
              }
              tooltip={{
                content: (
                  <div className="text-center">
                    <span className="font-bold">Range: 1 to 50. </span> <br />
                    More steps mean more time to generate the image and,
                    usually, a more artistic result. <br />
                    <span className="font-bold">
                      Fixed to 20 by the API. Not clear the impact on the
                      results.
                    </span>
                  </div>
                ),
              }}
            />
          </div>
        </div>
        <div className="flex w-full gap-x-3 mt-1">
          <div className="flex flex-col w-2/3" style={{ maxWidth: "235px" }}>
            <LabelWithTooltip
              className="mb-2 text-slate-400"
              label="Scheduler"
              tooltip={{
                content: (
                  <div className="text-center">
                    Schedulers define the methodology for adding noise to an{" "}
                    <br />
                    image or for updating a sample based on model outputs.{" "}
                    <br />
                    <span className="font-bold">
                      Note: Not all the Schedulers are accepted by the
                      controlnet model. <br />
                      If no scheduler is selected, the API applies
                      EulerDiscreteScheduler by default
                    </span>
                  </div>
                ),
              }}
            />
            <Select
              defaultValue={state.scheduler ? state.scheduler : undefined}
              onValueChange={(value: string) =>
                onHandleChange(
                  "scheduler",
                  value as InitialVariablesMenu["scheduler"]
                )
              }
            >
              <SelectTrigger className="w-full bg-white overflow-ellipsis">
                <SelectValue placeholder="Scheduler ID" />
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  {schedulers.map((schedulerId) => (
                    <SelectItem key={schedulerId} value={schedulerId}>
                      {schedulerId}
                    </SelectItem>
                  ))}
                </SelectGroup>
              </SelectContent>
            </Select>
          </div>
          <div className="w-1/3">
            <InputWithLabel
              id="GScale"
              label={<span className="text-slate-400">Guidance scale</span>}
              type="text"
              placeholder="7.5"
              value={state.guidanceScale}
              onChange={(value: any) => onHandleChange("guidanceScale", value)}
              tooltip={{
                content: (
                  <div className="text-center">
                    <span className="font-bold">Range: 1 to 20. </span> <br />
                    The more it is the more closely it follows the prompt.{" "}
                    <br />
                    However, after a certain value it becomes random. <br />
                    <span className="font-bold">
                      Values between 6 and 8 are recommended.
                    </span>
                  </div>
                ),
              }}
            />
          </div>
        </div>
      </div>
    </div>
  );
};
